<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'mainJs' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~mainJs.js',
                '/build/mainJs.js',
            ],
        ],
        'myBurgerJs' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~contactJs~myBurgerJs.js',
                '/build/myBurgerJs.js',
            ],
        ],
        'contactJs' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~contactJs~myBurgerJs.js',
                '/build/vendors~contactJs.js',
                '/build/contactJs.js',
            ],
        ],
        'mainCss' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/mainCss.css',
            ],
        ],
        'myBurgerHomeCss' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/myBurgerHomeCss.css',
            ],
        ],
        'myBurgerConnectCss' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/myBurgerConnectCss.css',
            ],
        ],
        'myBurgerAdminCss' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/myBurgerAdminCss.css',
            ],
        ],
        'myLoginCss' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/myLoginCss.css',
            ],
        ],
        'homeCss' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/homeCss.css',
            ],
        ],
    ],
],

]];
